### ISSUE TITLE
Empty Repos cannot be forked

### ISSUE THREAD

**Issue by jonchurch** [expressjs/.github#1]
This repo needs something in it before it can be forked, or PR's opened against it.

An empty readme, or .gitignore would suffice.

Same goes for the other two orgs' repos

**Comment by dougwilson** [comment]
Sorry, I realized that last night, just didn't get to pushing up a README to kick off a root commit yet today on these repos 😞

**Comment by jonchurch** [comment]
Because this will be reflected against other projects, I'd suggest an empty .gitignore on master, then we can start working in branches before merging things in. Or maybe a .github folder with an empty .gitignore

I.E. don't want to accidentally commit something across the whole org if it's missing in other repos.

**Comment by dougwilson** [comment]
Ah, the `.gitignore` is probably a better idea. Of course, not sure what to actually ignore, but it can be an empty file. Even an empty `.gitkeep` would do.

**Comment by dougwilson** [comment]
I realized I can just make an empty commit, even better. So all the repos are initialized with an empty tree and should be fork-able now. They all have the exact same tree, which may or may not help us latter :)

```
$ git init
$ git commit -m 'Initialize repository' --allow-empty
$ for o in expressjs pillarjs jshttp; do git remote add $o git@github.com:$o/.github.git; git push $o HEAD:refs/heads/m
aster; done
```

**Comment by AjayKusekar** [comment]
can i fork a empty repo. is there a solution ?
